# Названия типов (по профилям, регионам и примерам МО; метки упорядочены по убыванию размера)
K4:
  0: Малые сельские МО
  1: Индустриальные и средние города
  2: Столичные агломерации
  3: Ресурсный Север и Дальний Восток
K5:
  0: Малые сельские МО
  1: Малые города и районы со смешанной экономикой
  2: Индустриальные города и пригороды
  3: Столичные агломерации
  4: Ресурсный Север и Дальний Восток
